// Mocks generated by Mockito 5.4.4 from annotations
// in recipesoup/test/widget/screens/url_import_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:recipesoup/models/mood.dart' as _i8;
import 'package:recipesoup/models/recipe.dart' as _i7;
import 'package:recipesoup/models/recipe_analysis.dart' as _i3;
import 'package:recipesoup/providers/recipe_provider.dart' as _i6;
import 'package:recipesoup/services/openai_service.dart' as _i5;
import 'package:recipesoup/services/url_scraper_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeScrapedContent_0 extends _i1.SmartFake
    implements _i2.ScrapedContent {
  _FakeScrapedContent_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecipeAnalysis_1 extends _i1.SmartFake
    implements _i3.RecipeAnalysis {
  _FakeRecipeAnalysis_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UrlScraperService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUrlScraperService extends _i1.Mock implements _i2.UrlScraperService {
  MockUrlScraperService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ScrapedContent> scrapeRecipeFromUrl(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #scrapeRecipeFromUrl,
          [url],
        ),
        returnValue: _i4.Future<_i2.ScrapedContent>.value(_FakeScrapedContent_0(
          this,
          Invocation.method(
            #scrapeRecipeFromUrl,
            [url],
          ),
        )),
      ) as _i4.Future<_i2.ScrapedContent>);
}

/// A class which mocks [OpenAiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenAiService extends _i1.Mock implements _i5.OpenAiService {
  MockOpenAiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i3.RecipeAnalysis> analyzeImage(
    String? imageData, {
    _i5.LoadingProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeImage,
          [imageData],
          {#onProgress: onProgress},
        ),
        returnValue: _i4.Future<_i3.RecipeAnalysis>.value(_FakeRecipeAnalysis_1(
          this,
          Invocation.method(
            #analyzeImage,
            [imageData],
            {#onProgress: onProgress},
          ),
        )),
      ) as _i4.Future<_i3.RecipeAnalysis>);

  @override
  _i4.Future<_i3.RecipeAnalysis> analyzeText(
    String? blogText, {
    _i5.LoadingProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeText,
          [blogText],
          {#onProgress: onProgress},
        ),
        returnValue: _i4.Future<_i3.RecipeAnalysis>.value(_FakeRecipeAnalysis_1(
          this,
          Invocation.method(
            #analyzeText,
            [blogText],
            {#onProgress: onProgress},
          ),
        )),
      ) as _i4.Future<_i3.RecipeAnalysis>);

  @override
  _i4.Future<bool> checkApiHealth() => (super.noSuchMethod(
        Invocation.method(
          #checkApiHealth,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RecipeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeProvider extends _i1.Mock implements _i6.RecipeProvider {
  MockRecipeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i7.Recipe> get recipes => (super.noSuchMethod(
        Invocation.getter(#recipes),
        returnValue: <_i7.Recipe>[],
      ) as List<_i7.Recipe>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  List<_i7.Recipe> get todayMemories => (super.noSuchMethod(
        Invocation.getter(#todayMemories),
        returnValue: <_i7.Recipe>[],
      ) as List<_i7.Recipe>);

  @override
  List<_i7.Recipe> get recentRecipes => (super.noSuchMethod(
        Invocation.getter(#recentRecipes),
        returnValue: <_i7.Recipe>[],
      ) as List<_i7.Recipe>);

  @override
  List<_i7.Recipe> get favoriteRecipes => (super.noSuchMethod(
        Invocation.getter(#favoriteRecipes),
        returnValue: <_i7.Recipe>[],
      ) as List<_i7.Recipe>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> loadRecipes() => (super.noSuchMethod(
        Invocation.method(
          #loadRecipes,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addRecipe(_i7.Recipe? recipe) => (super.noSuchMethod(
        Invocation.method(
          #addRecipe,
          [recipe],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateRecipe(_i7.Recipe? updatedRecipe) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRecipe,
          [updatedRecipe],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRecipe(String? recipeId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRecipe,
          [recipeId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i7.Recipe> searchRecipes(
    String? query, {
    _i8.Mood? mood,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRecipes,
          [query],
          {#mood: mood},
        ),
        returnValue: <_i7.Recipe>[],
      ) as List<_i7.Recipe>);

  @override
  List<_i7.Recipe> searchByTag(String? tag) => (super.noSuchMethod(
        Invocation.method(
          #searchByTag,
          [tag],
        ),
        returnValue: <_i7.Recipe>[],
      ) as List<_i7.Recipe>);

  @override
  List<_i7.Recipe> getRecipesByMood(_i8.Mood? mood) => (super.noSuchMethod(
        Invocation.method(
          #getRecipesByMood,
          [mood],
        ),
        returnValue: <_i7.Recipe>[],
      ) as List<_i7.Recipe>);

  @override
  void selectRecipe(_i7.Recipe? recipe) => super.noSuchMethod(
        Invocation.method(
          #selectRecipe,
          [recipe],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearSelection() => super.noSuchMethod(
        Invocation.method(
          #clearSelection,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> toggleFavorite(String? recipeId) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [recipeId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setError(String? message) => super.noSuchMethod(
        Invocation.method(
          #setError,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
